package cn.wang;

public enum CalculationSearchType {
	
	SNAPSHOT, SEASON, ACCURACY, ACCIDENTAL_KILLS, SUCCESSFUL_MISSION_PERCENTAGE, 
	SUCCESSFUL_DEFEND_PERCENTAGE, SUCCESSFUL_ATTACK_PERCENTAGE, KILL_DEATH_RATE, ENEMY
}
